spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajsekharkundu22/configuration_properties.git
          clone-on-start: true
          
  application:
    name: config-server
server:
  port: 9093
 
 